apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx
 namespace: nginx-dev
spec:
 replicas: 1
 selector:
  matchLabels:
   app: nginx
 template:
  metadata:
   labels:
    app: nginx
  spec:
   containers:
   - image: nginx
     name: ellurukalyan/newrepo:latest

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-svc
  namespace: nginx-dev
spec:
  selector:
    app: nginx
    type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4567
